kind: pipeline
name: build and deploy

steps:
- name: test build
  image: 
- name: build/deploy
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: addysnip/dev
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:8}
    - ${DRONE_TAG}
  when:
    event:
    - push
    ref:
    - refs/head/main
    - refs/tags/*

